#include <armadillo>
#include <cmath>
#include <libwfa/export/export_cube_base.h>
#include <libwfa/libwfa_exception.h>
#include "export_cube_base_test.h"

using namespace arma;


namespace libwfa {

void export_cube_base_test::perform() throw(libtest::test_exception) {

    test_1();
}


namespace {

class export_cube_test : public export_cube_base {
private:
    struct system_data {
        grid3d grid;
        uvec atnum;
        mat coord;
        vec ao_exp;

        system_data() : grid(10, 0.5), atnum(2),
            coord(3, 2, fill::zeros), ao_exp(4) {

            atnum(0) = atnum(1) = 8;
            coord(2, 0) = -1.1; coord(2, 1) = 1.1;
            double c = 10.0;
            for (size_t i = 0; i < 4; i++, c /= 10.) ao_exp(i) = c;

        }
    };
    static system_data sys;

public:
    export_cube_test() :
        export_cube_base(sys.grid, sys.atnum, sys.coord, "export_cube_test_",
                8, 0, "Generated by libwfa::export_cube_test") { }

    size_t nao() const { return sys.coord.n_rows * sys.ao_exp.n_elem; }

private:
    virtual void evaluate_on_grid(const mat &pts, size_t npts, mat &b2g) {

        npts = std::min((size_t)pts.n_cols, npts);
        if (b2g.n_rows < npts || b2g.n_cols != nao()) {
            b2g.resize(npts, nao());
        }

        for (size_t j = 0, pos = 0; j < sys.coord.n_cols; j++) {

            for (size_t ipt = 0; ipt != npts; ipt++) {

                double d = norm(pts.col(ipt) - sys.coord.col(j), 2);
                for (size_t k = 0; k < sys.ao_exp.n_elem; k++, pos++) {
                    b2g(ipt, pos) = exp(-sys.ao_exp(k) * d * d);
                }
                pos -= sys.ao_exp.n_elem;
            }
            pos += sys.ao_exp.n_elem;
        }
    }

    virtual void evaluate_esp(const arma::mat &pts,
        size_t npts, const arma::mat &dens, arma::mat &esp) {}
};
export_cube_test::system_data export_cube_test::sys;

} // unnamed namespace

/** \brief Test construction of an empty grid
 **/
void export_cube_base_test::test_1() {

    static const char *testname = "export_cube_base_test::test_1()";

    try {

    export_cube_test ex;
    mat dm1(ex.nao(), ex.nao(), fill::randu);
    mat dm2(ex.nao(), ex.nao(), fill::randu);
    mat orb1(ex.nao(), 4, fill::randu);
    mat orb2(ex.nao(), 5, fill::randu);
    std::vector<size_t> i1(4, 0), i2(5, 0);
    for (size_t i = 0; i < 4; i++) i1[i] = 2 * i;
    for (size_t i = 0; i < 5; i++) i2[i] = i;

    ex.perform("dm1", "First test density matrix", dm1);
    ex.perform("dm2", "Second test density matrix", dm2);
    ex.perform("orb1", "First test density matrix", i1, orb1);
    ex.perform("orb2", "Second test density matrix", i2, orb2);

    ex.do_export();

    } catch (libwfa_exception &e) {
        fail_test(testname, __FILE__, __LINE__, e.what());
    }
}


} // namespace libwfa
